name: Lint Collection Docs

on:
  push:
    branches:
      - '**'

jobs:
  lint-collection-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install antsibull-docs
      - name: Install antsibull-docs
        run: |
          python -m pip install --upgrade pip
          pip install antsibull-docs

      # Run the lint command
      - name: Lint collection docs
        run: |
          antsibull-docs lint-collection-docs --plugin-docs .